### ISSUE TITLE
Genetic Super Terrain N3 knob

### ISSUE THREAD

**Issue by midiguru23** [docb/dbRackModules#3] opened 2022-01-03 19:29 UTC
When I turn the N3 knob in Genetic Super Terrain down to a low value, the output of the module dies. It can't be restored. Even the Initialize command doesn't bring back the output signal. This is with VCV Rack Pro 2.0.4 running in Windows 10.

**Comment by docb** [comment] 2022-01-03 19:46
hi, the problem is that i can not reproduce this.Could you provide all parameters M1,M2,N1,N2, N3, A,B -- the super formula curves are very sensible in some cases.

**Comment by docb** [comment] 2022-01-14 10:30
hi, finally i could reproduce it on the terrain "sin(sqr(y+x))*x+sqr(sin(x)*cos(y))" on the diagonal which produces higher voltages than +- 10V. It's related to my note in the manual:
"The speed of the point on some curves can vary dramatically which results in high frequencies (but also very interesting sounds) and may upset connected VCFs".
 
Here it upsets the internal DCBlocker.  

The reason why it cant be fixed by initialize is unclear, seems to be something in the VCVRack cable implementation.
I will check it and try to fix in the next version.
Thanks for your report!

**Comment by docb** [comment] 2022-08-04 04:18
Closing due to inactivity and fix.

**Closed as completed by docb** 2022-08-04 04:18 UTC
